import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import {
  Box,
  Button,
  Grid,
  GridItem,
  Heading,
  Text,
  VStack,
} from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import Setup from "@/components/Setup";
import TabsComponent from "@/components/TabsComponent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack align={"flex-start"} spacing={10} px={28}>
        <Navbar />

        <Grid templateColumns={"repeat(2, 1fr)"}>
          <GridItem>
            <Setup />
          </GridItem>
          <GridItem>
            <TabsComponent />
          </GridItem>
        </Grid>
      </VStack>
    </>
  );
}
